### PR TITLE
Add support for numbers in account names

### PR DESCRIPTION
**Pull request by lockjs**
Previosuly given the account name `Assets:Bank:Santander-123` auto complete would suggest `Assets:Bank:Santander-`

If the account name was `Assets:Bank:Santander-123-Current-Account` then auto complete would suggest  `Assets:Bank:Santander-` and `-Current-Account`

The updated regexp prevents the account name being split so that `Assets:Bank:Santander-123-Current-Account` will be suggested

### CODE REVIEW

**Comment by Lencerf** [comment]
Since Beancount actually allows any non-whitespace unicode characters in the account name, maybe `[A-Za-z:]+\\S+|\"([^\\\\\"]|\\\\\")*\"` is a better choice?

**Comment by lockjs** [comment]
I Agree, seems like a better option and would resolve [#20](https://github.com/Lencerf/vscode-beancount/issues/20)

I'll update the pull-request tomorrow.

Do you want me to bump the version number as well?

**Comment by Lencerf** [comment]
@lockjs Thanks!
I will handle the version number and update README.

**Comment by lockjs** [comment]
Updated the regex as you suggested.

I've also modified the language file to correctly highlight account names. You can see the non-ascii charachters weren't highlighted in the example in #20

**Pull request merged**
